version: "3.9"

services:
  app:
    image: <image-uri>
    environment:
      MY_ENV_VAR: "value"
      MY_EXISTING_ENV_VAR: "${MY_EXISTING_ENV_VAR}"
    volumes:
      - /mnt/datasets:/mnt/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
